apiVersion: v1
kind: ConfigMap

data:
  policy.csv: |
    g, github:ssejzer@techzer.com.ar, role:admin
    g, sejzer:ssejzer@techzer.com.ar, role:admin
  policy.default: role:readonly
  scopes: '[groups, email]'

metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
